easy_admin:
  entities:
    User:
      class: App\Entity\User
      label: Representantes y Administradores
      form:
        fields:
          - { property: 'username', label: 'Usuario (NIF en NEXUS)' }
          - { property: 'email', label: 'Correo electrónico' }
          - { property: 'enabled', label: '¿Activo?' }
          #- lastLogin
          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'roles', label: 'Perfil', type: 'choice', type_options: { multiple: true, choices: { 'Representante': 'ROLE_USER', 'Administrador': 'ROLE_ADMIN' } } }
      new:
        fields:
          - { property: 'username', label: 'Usuario (NIF en NEXUS)' }
          - { property: 'email', label: 'Correo electrónico' }
          - { property: 'plainPassword', label: 'Contraseña (ALIAS en NEXUS)', type: 'text', type_options: { required: true } }
          - { property: 'roles', label: 'Perfil', type: 'choice', type_options: { multiple: true, choices: { 'Representante': 'ROLE_USER', 'Administrador': 'ROLE_ADMIN' } } }
      edit:
        fields:
          - { property: 'username', label: 'Usuario (NIF en NEXUS)' }
          - { property: 'email', label: 'Correo electrónico' }
          - { property: 'enabled', label: '¿Activo?' }
          - { property: 'roles', label: 'Perfil', type: 'choice', type_options: { multiple: true, choices: { 'Representante': 'ROLE_USER', 'Administrador': 'ROLE_ADMIN' } } }
      list:
        fields:
          - { property: 'username', label: 'Usuario (NIF en NEXUS)' }
          - { property: 'email', label: 'Correo electrónico' }
          - { property: 'enabled', label: '¿Activo?' }
