easy_admin:
  entities:
    Linepedi:
      class: App\Entity\Linepedi
      label: 'Líneas de Pedido'
      controller: App\Controller\Model\LineasController

      form:
        fields:
          - { property: pedido, label: 'Pedido', sortable: true }
          - { property: articulo, label: 'Artículo', sortable: false }
          - { property: unidades, label: 'Unidades', sortable: false }

      list:
        fields:
#          #- { property: id, label: 'Identificador', sortable: false }
          - { property: pedido, label: 'Pedido', sortable: true permission: ROLE_SUPER_ADMIN}
          - { property: articulo, label: 'Artículo', sortable: false }
          - { property: unidades, label: 'Unidades', sortable: false }
      new:
        fields:
          #- { property: id, label: 'Identificador', type_options: { required: true} }
          - { property: pedido, label: 'Pedido', type_options: { required: true} }
          - { property: articulo, label: 'Artículo', type_options: { required: true} }
          - { property: unidades, label: 'Unidades', type_options: { required: true} }